---
title: "Aribnb Price Model "
author: "Chang Wen-Chuan"
date: "2018 Apr 21"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#import data 
```{r}
#import data
Sys.setlocale("LC_ALL", "English")
Airdata_or<- as.data.frame(read.csv("listings_detail.csv",quote = "\"",stringsAsFactors = TRUE))

# select numerical variable 
Airdata<-Airdata_or
str(Airdata)
col_name_or<-colnames(Airdata)
temp<-c()

for(i in 1:ncol(Airdata)){
  if(class(Airdata[,i])=="factor"){
    temp<-append(temp,i)
  }
}
Airdata<-Airdata[,-temp]

```
## Location issue

```{r}
summary(Airdata_or$zipcode)

library(ggplot2)
ggplot(data=Airdata_or)+geom_point(aes(x=zipcode,y=review_scores_location))+labs(title="zip VS survey",x="zipcode",y="review score")
```

## use KNN to define review_scores_location
```{r}
#select data only containing latitude and longitude  and review_scores_location
DA_KNN<- Airdata
colnames(DA_KNN)
var_KNN<-c("latitude","longitude","review_scores_location")
DA_KNN<-DA_KNN[,var_KNN]
DA_KNN<-subset(DA_KNN,review_scores_location!="NA")
summary(DA_KNN)
## assign training dataset and test dataset
set.seed(1000)
data_sample <- sample(2, nrow(DA_KNN), replace=TRUE, prob=c(0.7, 0.3))
data_training<- DA_KNN[data_sample==1,1:2]
data_test<-DA_KNN[data_sample==2,1:2]
##set Y variables
DA_KNN$review_scores_location<-as.factor(DA_KNN$review_scores_location)
summary(DA_KNN$review_scores_location)
data.trainLabels <- DA_KNN[data_sample==1, 3]
data.testLabels <- DA_KNN[data_sample==2, 3]
##Perform the KNN with K=3
library(FNN)
library(gmodels)
data_pred <- knn(train = data_training, test = data_test, cl=data.trainLabels, k=3)
data.pred <- CrossTable(data.testLabels, data_pred, prop.chisq = FALSE)
##calculate accuracy 
data.pred.accuracy.table=data.pred$t
data.pred.accuracy=sum(data.pred.accuracy.table[row(data.pred.accuracy.table)==col(data.pred.accuracy.table)])/sum(data.pred.accuracy.table)
data.pred.accuracy

##perform KNN loop from K=2 to K=10
t=2:10
KNN_data<-data.frame(Number=t,Accuracy=c(0,0,0,0,0,0,0,0,0))
for(i in t){
  library(FNN)
  library(gmodels)
  data_pred <- knn(train=data_training,test=data_test,cl=data.trainLabels, k=i)
  data.pred <- CrossTable(data.testLabels, data_pred, prop.chisq =FALSE)
  ##calculate accuracy 
  data.pred.accuracy.table=data.pred$t
  data.pred.accuracy=sum(data.pred.accuracy.table[row(data.pred.accuracy.table)==col(data.pred.accuracy.table)])/sum(data.pred.accuracy.table)
  KNN_data[i-1,2]<-data.pred.accuracy
}
KNN_data
write.table(KNN_data, file = "Accuracy.CSV", sep = ",")
library(lattice)
cloud(x=review_scores_location~latitude+longitude,
data=DA_KNN)
library(ggplot2)
KNN_data
ggplot(data=KNN_data)+geom_point(aes(x=Number,y=Accuracy))+labs(title="the accuracy of KNN",x="the number of K",y="accuracy")

```

